### ISSUE TITLE
Feature - Select multiple labels

### ISSUE THREAD

**Issue by Bashamega** [Bashamega/github-issue-finder#1]
The feature request is to be able to select multiple tags at a time

**Comment by matthiasmulzet** [comment]
Hey there, I'm interested in contributing to this project!

I have a few questions that I'd like to clarify:

1. Currently, it seems that you can only select one tag (e.g., html), and only that specific tag will be applied to the search. Is my understanding correct?

2. The new behaviour should be that users can select multiple tags (e.g., html, css, documentation), and all selected tags will be applied to the search? 

Looking forward to your guidance on these questions. Excited to get involved and contribute to the project!

**Comment by Bashamega** [comment]
> Hey there, I'm interested in contributing to this project!
> 
> I have a few questions that I'd like to clarify:
> 
> 1. Currently, it seems that you can only select one tag (e.g., html), and only that specific tag will be applied to the search. Is my understanding correct?
> 2. The new behaviour should be that users can select multiple tags (e.g., html, css, documentation), and all selected tags will be applied to the search?
> 
> Looking forward to your guidance on these questions. Excited to get involved and contribute to the project!

Correct this is it, if you want I can assign you

**Comment by matthiasmulzet** [comment]
yeah, i will take this

**Comment by Bashamega** [comment]
@matthiasmulzet doone

**Comment by matthiasmulzet** [comment]
thanks but i can't start the project. I guess there are more things to do, like install next.js. Also for what do i need a .env file with my token ?
Example of an Error i get: 
`Error occurred prerendering page "/500". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of null (reading 'useContext')`

**Comment by Bashamega** [comment]
@matthiasmulzet 
You will need the .env because we use a token to get the data from the [github api](https://docs.github.com/en/rest). Just create a personal token and insert it in the .env with TOKEN = . so add this line
`TOKEN = "yourtoken"`

**Comment by matthiasmulzet** [comment]
> @matthiasmulzet You will need the .env because we use a token to get the data from the [github api](https://docs.github.com/en/rest). Just create a personal token and insert it in the .env with TOKEN = . so add this line `TOKEN = "yourtoken"`

thanks, for the info. I'm on it.

**Comment by Bashamega** [comment]
> > @matthiasmulzet You will need the .env because we use a token to get the data from the [github api](https://docs.github.com/en/rest). Just create a personal token and insert it in the .env with TOKEN = . so add this line `TOKEN = "yourtoken"`
> 
> thanks, for the info. I'm on it.

Great
